# -*- coding: utf-8 -*-
"""GROUP_NUMBER (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xEwEy8lFEmxF-SfTYAXytwkzLl70WRp9

# SleepWise - Phase 2 Model Implementation and Evaluation

This notebook implements the Phase 2 requirements for the SleepWise project:
- End-to-end model development from scratch
- Data preprocessing and label creation
- Multiple classification models
- Hyperparameter tuning
- Evaluation on **test data**
- Metrics: **Accuracy, Precision, Recall, F1-Score, Confusion Matrix**
- Cross-validation and feature importance analysis

## How to use this notebook
1. Place the Kaggle dataset CSV in the same folder as this notebook, or update the `DATA_PATH` below.
2. Run all cells in order.
3. Export the finished notebook and rename it with your **group number** before submission.

Recommended final filename:
`GROUP_NUMBER.ipynb`
"""

# Core libraries
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay
)
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score, GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

RANDOM_STATE = 42
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 150)

"""## 1. Load the dataset

This notebook is built for the Kaggle Sleep Efficiency dataset mentioned in the project plan.
If your CSV has a different name, just update `DATA_PATH`.
"""

# Update this if your file has a different name
DATA_PATH = "Sleep_Efficiency.csv"

df = pd.read_csv(DATA_PATH)
print("Dataset shape:", df.shape)
df.head()

"""## 2. Initial data inspection"""

print("Column names:")
print(df.columns.tolist())
print("\nData types:")
display(df.dtypes)
print("\nMissing values:")
display(df.isnull().sum().sort_values(ascending=False))
print("\nDuplicate rows:", df.duplicated().sum())

"""## 3. Data cleaning and target creation

The original project proposal states that the sleep efficiency score should be converted into:
- Poor Sleep
- Moderate Sleep
- Good Sleep

### Default thresholds used in this notebook
These thresholds are reasonable and easy to explain in the report:
- `sleep_efficiency < 0.75` -> Poor Sleep
- `0.75 <= sleep_efficiency < 0.85` -> Moderate Sleep
- `sleep_efficiency >= 0.85` -> Good Sleep

You can adjust them if your instructor or team decides on different boundaries.
"""

# Standardize column names for easier handling
df.columns = [c.strip().lower().replace(" ", "_") for c in df.columns]

# Remove duplicates
df = df.drop_duplicates().copy()

# Identify likely target column
possible_target_cols = [c for c in df.columns if "sleep_efficiency" in c]
if not possible_target_cols:
    raise ValueError("Could not find the sleep_efficiency column. Check your dataset columns.")

target_score_col = possible_target_cols[0]
print("Using sleep score column:", target_score_col)

# Create categorical target
def categorize_sleep_efficiency(x):
    if pd.isna(x):
        return np.nan
    if x < 0.75:
        return "Poor Sleep"
    elif x < 0.85:
        return "Moderate Sleep"
    else:
        return "Good Sleep"

df["sleep_quality"] = df[target_score_col].apply(categorize_sleep_efficiency)

# Drop rows where target cannot be created
df = df.dropna(subset=["sleep_quality"]).copy()

print("Cleaned dataset shape:", df.shape)
display(df["sleep_quality"].value_counts())
df.head()
# (existing code in Cell 3 above...)

# ADD THIS at the bottom of Cell 3:
if "bedtime" in df.columns:
    df["bedtime"] = pd.to_datetime(df["bedtime"]).dt.hour
if "wakeup_time" in df.columns:
    df["wakeup_time"] = pd.to_datetime(df["wakeup_time"]).dt.hour

print("bedtime sample values:", df["bedtime"].head())
print("wakeup_time sample values:", df["wakeup_time"].head())

"""## 4. Optional feature cleanup

To avoid leakage, the original numerical sleep efficiency score is removed from features after creating the label.
If there are identifier columns, they are also removed.
"""

# Remove identifier-like columns if present
identifier_like_cols = [c for c in df.columns if c in ["id", "index", "person_id", "record_id"]]
print("Dropping identifier columns:", identifier_like_cols)
# Remove the original sleep efficiency score from X to prevent leakage
drop_cols = identifier_like_cols + [target_score_col, "sleep_quality"]

X = df.drop(columns=drop_cols, errors="ignore").copy()
y = df["sleep_quality"].copy()

print("Feature matrix shape:", X.shape)
print("Target shape:", y.shape)
print("Features used:")
print(X.columns.tolist())



"""## 5. Train-test split

As required in the proposal:
- Training data = 80%
- Testing data = 20%

The split is stratified to preserve class balance.
"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.20,
    random_state=RANDOM_STATE,
    stratify=y
)

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("\nTrain class distribution:")
display(y_train.value_counts(normalize=True).rename("proportion"))
print("\nTest class distribution:")
display(y_test.value_counts(normalize=True).rename("proportion"))

"""## 6. Preprocessing pipeline

The project proposal requires:
- handling missing values
- encoding categorical variables
- normalizing/scaling numerical features where necessary

This is done using a `ColumnTransformer`.
"""

numeric_features = X_train.select_dtypes(include=["number"]).columns.tolist()
categorical_features = X_train.select_dtypes(exclude=["number"]).columns.tolist()

print("Numeric features:", numeric_features)
print("Categorical features:", categorical_features)

numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_features),
        ("cat", categorical_transformer, categorical_features)
    ]
)

"""## 7. Define models and hyperparameter grids

Models required by the proposal:
- Logistic Regression
- Decision Tree
- Random Forest
- Support Vector Machine (SVM)

GridSearchCV is used for tuning.
"""

models_and_grids = {
    "Logistic Regression": {
        "model": LogisticRegression(max_iter=5000, random_state=RANDOM_STATE),
        "params": {
            "classifier__C": [0.1, 1, 10],
            "classifier__solver": ["lbfgs"]
        }
    },
    "Decision Tree": {
        "model": DecisionTreeClassifier(random_state=RANDOM_STATE),
        "params": {
            "classifier__max_depth": [3, 5, 10, None],
            "classifier__min_samples_split": [2, 5, 10],
            "classifier__min_samples_leaf": [1, 2, 4]
        }
    },
    "Random Forest": {
        "model": RandomForestClassifier(random_state=RANDOM_STATE),
        "params": {
            "classifier__n_estimators": [100, 200],
            "classifier__max_depth": [None, 5, 10],
            "classifier__min_samples_split": [2, 5],
            "classifier__min_samples_leaf": [1, 2]
        }
    },
    "SVM": {
        "model": SVC(random_state=RANDOM_STATE),
        "params": {
            "classifier__C": [0.1, 1, 10],
            "classifier__kernel": ["linear", "rbf"],
            "classifier__gamma": ["scale", "auto"]
        }
    }
}

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)

"""## 8. Train, tune, and evaluate all models

This section:
- builds a full preprocessing + model pipeline
- tunes the model with GridSearchCV on training data
- evaluates the final tuned model on test data
- saves the confusion matrix and classification report
"""

results = []
best_estimators = {}
reports = {}
conf_matrices = {}

for model_name, config in models_and_grids.items():
    print("=" * 80)
    print(f"Training: {model_name}")

    pipeline = Pipeline(steps=[
        ("preprocessor", preprocessor),
        ("classifier", config["model"])
    ])

    grid = GridSearchCV(
        estimator=pipeline,
        param_grid=config["params"],
        cv=cv,
        scoring="f1_weighted",
        n_jobs=-1
    )

    grid.fit(X_train, y_train)
    best_model = grid.best_estimator_
    best_estimators[model_name] = best_model

    y_pred = best_model.predict(X_test)

    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average="weighted", zero_division=0)
    recall = recall_score(y_test, y_pred, average="weighted", zero_division=0)
    f1 = f1_score(y_test, y_pred, average="weighted", zero_division=0)

    cv_score = cross_val_score(best_model, X_train, y_train, cv=cv, scoring="f1_weighted", n_jobs=-1).mean()

    cm = confusion_matrix(y_test, y_pred, labels=best_model.classes_)
    conf_matrices[model_name] = (cm, best_model.classes_)

    report = classification_report(y_test, y_pred, zero_division=0, output_dict=True)
    reports[model_name] = pd.DataFrame(report).transpose()

    results.append({
        "Model": model_name,
        "Best Parameters": grid.best_params_,
        "CV F1 (mean)": round(cv_score, 4),
        "Test Accuracy": round(accuracy, 4),
        "Test Precision": round(precision, 4),
        "Test Recall": round(recall, 4),
        "Test F1-Score": round(f1, 4)
    })

results_df = pd.DataFrame(results).sort_values(by="Test F1-Score", ascending=False).reset_index(drop=True)
results_df

"""## 9. Model comparison table

This table fulfills the core performance analysis requirement.
"""

display(results_df)

"""## 10. Plot confusion matrices for all models"""

for model_name, (cm, labels) in conf_matrices.items():
    fig, ax = plt.subplots(figsize=(6, 5))
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=labels)
    disp.plot(ax=ax, values_format="d", cmap="Blues", colorbar=False)
    plt.title(f"Confusion Matrix - {model_name}")
    plt.grid(False)
    plt.show()

"""## 11. Detailed classification reports"""

for model_name, report_df in reports.items():
    print("=" * 80)
    print(model_name)
    display(report_df.round(4))

"""## 12. Select the best model

We select the model with the highest **test F1-score**.
If your instructor prefers another selection criterion, you can change it here.
"""

best_model_name = results_df.iloc[0]["Model"]
best_model = best_estimators[best_model_name]

print("Best model selected:", best_model_name)
print("\nBest model parameters:")
best_row = results_df[results_df["Model"] == best_model_name].iloc[0]
print(best_row["Best Parameters"])

"""## 13. Feature importance / interpretability

The proposal asks for identifying the most influential lifestyle factors.

- If the best model is Random Forest, we use built-in feature importances.
- If it is Logistic Regression or linear SVM, we use coefficient magnitudes.
- If it is a non-linear SVM, feature importance is not directly available, so a note is shown.
"""

# Helper: get transformed feature names from the preprocessor
def get_feature_names_from_column_transformer(column_transformer):
    output_features = []
    for name, transformer, columns in column_transformer.transformers_:
        if name == "remainder":
            continue

        if hasattr(transformer, "named_steps"):
            last_step = list(transformer.named_steps.values())[-1]
            if hasattr(last_step, "get_feature_names_out"):
                try:
                    names = last_step.get_feature_names_out(columns)
                except:
                    names = columns
            else:
                names = columns
        else:
            if hasattr(transformer, "get_feature_names_out"):
                try:
                    names = transformer.get_feature_names_out(columns)
                except:
                    names = columns
            else:
                names = columns
        output_features.extend(names)
    return output_features

preprocessor_fitted = best_model.named_steps["preprocessor"]
classifier_fitted = best_model.named_steps["classifier"]
feature_names = get_feature_names_from_column_transformer(preprocessor_fitted)

importance_df = None

if hasattr(classifier_fitted, "feature_importances_"):
    importances = classifier_fitted.feature_importances_
    importance_df = pd.DataFrame({
        "Feature": feature_names,
        "Importance": importances
    }).sort_values(by="Importance", ascending=False)

elif hasattr(classifier_fitted, "coef_"):
    coef = classifier_fitted.coef_
    if coef.ndim == 2:
        importances = np.mean(np.abs(coef), axis=0)
    else:
        importances = np.abs(coef)
    importance_df = pd.DataFrame({
        "Feature": feature_names,
        "Importance": importances
    }).sort_values(by="Importance", ascending=False)

if importance_df is not None:
    display(importance_df.head(15).reset_index(drop=True))

    plt.figure(figsize=(10, 6))
    top_n = importance_df.head(10).sort_values(by="Importance", ascending=True)
    plt.barh(top_n["Feature"], top_n["Importance"])
    plt.title(f"Top 10 Important Features - {best_model_name}")
    plt.xlabel("Importance")
    plt.ylabel("Feature")
    plt.show()
else:
    print(f"Direct feature importance is not available for {best_model_name}.")
    print("If needed, permutation importance can be added.")

"""## 14. Automated performance analysis summary

This cell creates a ready-to-use paragraph for your report or presentation.
"""

summary_lines = []

summary_lines.append(
    f"The project compared four supervised classification models: Logistic Regression, Decision Tree, Random Forest, and SVM."
)
summary_lines.append(
    f"Using GridSearchCV with 5-fold stratified cross-validation, the best-performing model was {best_model_name}."
)

best_metrics = results_df.iloc[0]
summary_lines.append(
    f"On the held-out test set, the selected model achieved an accuracy of {best_metrics['Test Accuracy']:.4f}, "
    f"precision of {best_metrics['Test Precision']:.4f}, recall of {best_metrics['Test Recall']:.4f}, "
    f"and F1-score of {best_metrics['Test F1-Score']:.4f}."
)
summary_lines.append(
    f"The confusion matrix shows how well the model distinguishes between Poor Sleep, Moderate Sleep, and Good Sleep classes."
)

if importance_df is not None:
    top_features = importance_df.head(5)["Feature"].tolist()
    summary_lines.append(
        "Feature analysis suggests that the most influential variables include: "
        + ", ".join(top_features) + "."
    )

summary_lines.append(
    "Overall, the model demonstrates the feasibility of predicting sleep quality from behavioral and lifestyle variables, "
    "which supports the objective of the SleepWise system."
)

performance_summary = " ".join(summary_lines)
print(performance_summary)

"""## 15. Save final artifacts

This section saves:
- model comparison results
- detailed classification reports
- top feature importance table

These files can support your report and presentation.
"""

results_df.to_csv("model_comparison_results.csv", index=False)

# Save each classification report
for model_name, report_df in reports.items():
    safe_name = model_name.lower().replace(" ", "_")
    report_df.to_csv(f"{safe_name}_classification_report.csv")

if importance_df is not None:
    importance_df.to_csv("feature_importance.csv", index=False)

print("Artifacts saved successfully.")

"""## 16. Optional deployment-ready prediction helper

This small function can be reused later for a simple interface.
It takes a dictionary of user inputs and returns the predicted sleep class.
"""

def predict_sleep_quality(input_dict, model=best_model):
    input_df = pd.DataFrame([input_dict])
    prediction = model.predict(input_df)[0]
    return prediction

sample_good = {
    'age': 65,
    'gender': 'Female',
    'bedtime': 1,
    'wakeup_time': 7,
    'sleep_duration': 6.0,
    'rem_sleep_percentage': 18,
    'deep_sleep_percentage': 70,
    'light_sleep_percentage': 12,
    'awakenings': 0.0,
    'caffeine_consumption': 0.0,
    'alcohol_consumption': 0.0,
    'smoking_status': 'Yes',
    'exercise_frequency': 3.0
}

sample_poor = {
    'age': 69,
    'gender': 'Male',
    'bedtime': 2,
    'wakeup_time': 9,
    'sleep_duration': 7.0,
    'rem_sleep_percentage': 19,
    'deep_sleep_percentage': 28,
    'light_sleep_percentage': 53,
    'awakenings': 3.0,
    'caffeine_consumption': 0.0,
    'alcohol_consumption': 3.0,
    'smoking_status': 'Yes',
    'exercise_frequency': 3.0
}

sample_moderate = {
    'age': 57,
    'gender': 'Male',
    'bedtime': 1,
    'wakeup_time': 9,
    'sleep_duration': 8.0,
    'rem_sleep_percentage': 27,
    'deep_sleep_percentage': 55,
    'light_sleep_percentage': 18,
    'awakenings': 3.0,
    'caffeine_consumption': 0.0,
    'alcohol_consumption': 3.0,
    'smoking_status': 'No',
    'exercise_frequency': 3.0
}

print("Test 1 (Expected - Good Sleep)    :", predict_sleep_quality(sample_good))
print("Test 2 (Expected - Poor Sleep)    :", predict_sleep_quality(sample_poor))
print("Test 3 (Expected - Moderate Sleep):", predict_sleep_quality(sample_moderate))